CREATE TABLE IF NOT EXISTS `users` (
	`id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`content` INT(10) NOT NULL,
	`key` VARCHAR(255) NOT NULL,
	`value` VARCHAR(255) NOT NULL,
	`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`),
	INDEX `pair` (`key`, `value`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci
;